sha256 is changed
`https://download.dbeaver.com/community/21.1.0/checksum/dbeaver-ce-21.1.0-macos.dmg.sha256` content is different.
```bash
==> Purging files for version 21.1.0 of Cask dbeaver-community
Error: dbeaver-community: SHA256 mismatch
Expected: d8500c45917480c2532db584e0470b9c015abd25a09ce68beafd7a70dba3c3ff
  Actual: dec806a96ea9609e45357ca31685e39495973d22ee1612099b73756cfe740573
    File: ../Library/Caches/Homebrew/downloads/b32ade3e2b41e43fddc587ddbcc5fc48e23b6be7de2b69297b4e0b8e17c66134--dbeaver-ce-21.1.0-macos.dmg
To retry an incomplete download, remove the file above.
```